### ISSUE TITLE
Export GTFS to JSON

### ISSUE THREAD

**Issue by brechtvdv** [transitland/mapzen-gtfs#16]
Hi

I'm trying to generate JSON with correct OneStopIds from a sample GTFS dump.

Everything works fine untill I run:
```
>>> f.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Feed' object has no attribute 'json'
```
Does somebody know what I'm doing wrong? I'm still new to Python.

Is this the right way to make a feed with OneStopIds for transitland-datastore?

Thanks in advance
Brecht

**Comment by brechtvdv** [comment]
I was able to generate JSON with the following script:
```python
import mzgtfs.feed
import json

gtfs = mzgtfs.feed.Feed('gtfs.zip')
gtfs.preload()
gtfs = gtfs.agency('0')

with open('gtfs.json','w') as outfile:
    json.dump(gtfs.json(),outfile)
```

**Comment by drewda** [comment]
@brechtvdv glad to hear you've resolved your issue. Thanks for sharing your solution!
