### ISSUE TITLE
Less strict validations?

### ISSUE THREAD

**Issue by laidig** [transitland/mapzen-gtfs#20]
We have a use case for including trips with service_ids that are not in the calendar-- they can be activated on short notice (e.g. snow days) with just a calendar_dates change.

The problem is that these fail gtfs_feed.validate(). Not the best when you are trying to build a calendar editor to cover that use case. 

Would you accept a pull request that adds a strict mode (default true), that when set to false ignores these issues?

**Comment by irees** [comment]
hi @laidig

That is a good idea. What other validations would be relaxed with strict=false, which values are 'good enough' even if not strictly valid. Currently, the validation is currently split into two parts: internal validation and relational validation. As an alternative to a less strict mode, would a flag to skip checking relations satisfy your requirement?

**Comment by laidig** [comment]
Hey Ian, no PR ready yet, this was more of a discussion. 

Skipping relation checking seems like a much better idea. I'll get a PR to you.
