### ISSUE TITLE
How to update stop_sequence?

### ISSUE THREAD

**Issue by laidig** [transitland/mapzen-gtfs#25]
I'm trying to update the stop_sequence of a trip, but can't quite figure out how to reach in there. Any ideas? 

    for trip in feed.trips():
     seq = trip.stop_sequence()

     #remove stops with no pickup and dropoff allowed from the sequence
     seq = [s for s in seq if not (s['pickup_type'] == "1" and s['drop_off_type'] == "1")]

     #does not work
     trip.set('stop_sequence', seq)

     #does not work either
     trip.add_child(seq)

     #check for remaining stops
     for s in trip.stop_sequence():
        if s['pickup_type'] == "1" and s['drop_off_type'] == "1":
            print s['stop_id']

**Comment by irees** [comment]
hi @laidig 

Ah, good catch. It's not properly documented, and I just noticed I don't have methods for removing/reassigning associations. The `stop_times` associated with a trip are available in `trip.children()`, and `trip.stop_sequence()` returns the children sorted by `stop_sequence`. The underlying attribute is `trip._children` and you should be able to manipulate this set, or assign it to your filtered list. This may be buggy but worth a shot.

```
>>> trip
<Trip BFC2>
>>> trip.children()
set([<StopTime None>, <StopTime None>])
>>> trip.stop_sequence() # children sorted by stop_sequence
[<StopTime None>, <StopTime None>]
>>> seq = [i for i in trip.stop_sequence() if i.get('stop_sequence') == '1']
>>> seq
[<StopTime None>]
>>> trip._children = set(seq)
>>> trip.stop_sequence()
[<StopTime None>]
```

**Comment by laidig** [comment]
Looks like it. Thanks!
